// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_id = $1::uuid)
  AND ($2::text IS NULL OR action = $2::text)
  AND ($3::text IS NULL OR target_type = $3::text)
  AND ($4::text IS NULL OR target_id = $4::text)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR created_at <= $6::timestamptz)
`

type CountAuditLogsParams struct {
	ActorID    *uuid.UUID
	Action     *string
	TargetType *string
	TargetID   *string
	FromTime   *time.Time
	ToTime     *time.Time
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, actor_email, action, target_type, target_id, metadata, ip, user_agent, created_at FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_id = $1::uuid)
  AND ($2::text IS NULL OR action = $2::text)
  AND ($3::text IS NULL OR target_type = $3::text)
  AND ($4::text IS NULL OR target_id = $4::text)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR created_at <= $6::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $8 OFFSET $7
`

type ListAuditLogsParams struct {
	ActorID      *uuid.UUID
	Action       *string
	TargetType   *string
	TargetID     *string
	FromTime     *time.Time
	ToTime       *time.Time
	ResultOffset int32
	ResultLimit  int32
}

// Необязательные фильтры через sqlc.narg: NULL означает «не фильтровать»
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.FromTime,
		arg.ToTime,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAuditLog = `-- name: WriteAuditLog :exec
INSERT INTO audit_logs (actor_id, actor_email, action, target_type, target_id, metadata, ip, user_agent, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9::timestamptz, now()))
`

type WriteAuditLogParams struct {
	ActorID    *uuid.UUID
	ActorEmail string
	Action     string
	TargetType string
	TargetID   string
	Metadata   []byte
	Ip         string
	UserAgent  string
	CreatedAt  *time.Time
}

func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog,
		arg.ActorID,
		arg.ActorEmail,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}
