// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO super_admin_invitations (email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	Email     string
	Role      SuperAdminRole
	TokenHash []byte
	InvitedBy *uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (SuperAdminInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i SuperAdminInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasPendingInvitation = `-- name: HasPendingInvitation :one
SELECT EXISTS (
    SELECT 1 FROM super_admin_invitations
    WHERE email = $1 AND accepted_at IS NULL
) AS exists
`

func (q *Queries) HasPendingInvitation(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingInvitation, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
