// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_template.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMessageTemplate = `-- name: GetMessageTemplate :one
SELECT key, body, updated_at, updated_by FROM message_templates WHERE key = $1
`

func (q *Queries) GetMessageTemplate(ctx context.Context, key string) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, getMessageTemplate, key)
	var i MessageTemplate
	err := row.Scan(
		&i.Key,
		&i.Body,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateMessageTemplate = `-- name: UpdateMessageTemplate :one
UPDATE message_templates
SET body = $2, updated_at = $3, updated_by = $4
WHERE key = $1
RETURNING key, body, updated_at, updated_by
`

type UpdateMessageTemplateParams struct {
	Key       string
	Body      string
	UpdatedAt *time.Time
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpdateMessageTemplate(ctx context.Context, arg UpdateMessageTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, updateMessageTemplate,
		arg.Key,
		arg.Body,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i MessageTemplate
	err := row.Scan(
		&i.Key,
		&i.Body,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
