// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type SuperAdminRole string

const (
	SuperAdminRoleOwner   SuperAdminRole = "owner"
	SuperAdminRoleAdmin   SuperAdminRole = "admin"
	SuperAdminRoleSupport SuperAdminRole = "support"
	SuperAdminRoleViewer  SuperAdminRole = "viewer"
)

func (e *SuperAdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SuperAdminRole(s)
	case string:
		*e = SuperAdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for SuperAdminRole: %T", src)
	}
	return nil
}

type NullSuperAdminRole struct {
	SuperAdminRole SuperAdminRole
	Valid          bool // Valid is true if SuperAdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSuperAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.SuperAdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SuperAdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSuperAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SuperAdminRole), nil
}

func (e SuperAdminRole) Valid() bool {
	switch e {
	case SuperAdminRoleOwner,
		SuperAdminRoleAdmin,
		SuperAdminRoleSupport,
		SuperAdminRoleViewer:
		return true
	}
	return false
}

func AllSuperAdminRoleValues() []SuperAdminRole {
	return []SuperAdminRole{
		SuperAdminRoleOwner,
		SuperAdminRoleAdmin,
		SuperAdminRoleSupport,
		SuperAdminRoleViewer,
	}
}

type SuperAdminStatus string

const (
	SuperAdminStatusActive    SuperAdminStatus = "active"
	SuperAdminStatusSuspended SuperAdminStatus = "suspended"
)

func (e *SuperAdminStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SuperAdminStatus(s)
	case string:
		*e = SuperAdminStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SuperAdminStatus: %T", src)
	}
	return nil
}

type NullSuperAdminStatus struct {
	SuperAdminStatus SuperAdminStatus
	Valid            bool // Valid is true if SuperAdminStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSuperAdminStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SuperAdminStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SuperAdminStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSuperAdminStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SuperAdminStatus), nil
}

func (e SuperAdminStatus) Valid() bool {
	switch e {
	case SuperAdminStatusActive,
		SuperAdminStatusSuspended:
		return true
	}
	return false
}

func AllSuperAdminStatusValues() []SuperAdminStatus {
	return []SuperAdminStatus{
		SuperAdminStatusActive,
		SuperAdminStatusSuspended,
	}
}

type AuditLog struct {
	ID         int64
	ActorID    *uuid.UUID
	ActorEmail string
	Action     string
	TargetType string
	TargetID   string
	Metadata   []byte
	Ip         string
	UserAgent  string
	CreatedAt  time.Time
}

type RefreshToken struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SessionID     uuid.UUID
	TokenHash     []byte
	ExpiresAt     time.Time
	UsedAt        *time.Time
	RevokedAt     *time.Time
	RevokedReason *string
	ReplacedBy    *uuid.UUID
	UserAgent     string
	Ip            string
	CreatedAt     time.Time
}

type SuperAdminUser struct {
	ID                  uuid.UUID
	Email               string
	FullName            string
	PasswordHash        string
	Role                SuperAdminRole
	Status              SuperAdminStatus
	TotpSecret          *string
	TotpEnrolledAt      *time.Time
	FailedLoginAttempts int32
	LockedUntil         *time.Time
	LastLoginAt         *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
