// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, user_id, session_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, session_id, token_hash, expires_at, used_at, revoked_at, revoked_reason, replaced_by, user_agent, ip, created_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SessionID uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent string
	Ip        string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, session_id, token_hash, expires_at, used_at, revoked_at, revoked_reason, replaced_by, user_agent, ip, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens
SET used_at = $2,
    replaced_by = $3
WHERE id = $1 AND used_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	ID         uuid.UUID
	UsedAt     *time.Time
	ReplacedBy *uuid.UUID
}

// Условие used_at IS NULL делает операцию идемпотентной: параллельный повтор
// того же refresh не перезапишет связь и не спрячет факт переиспользования
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.ID, arg.UsedAt, arg.ReplacedBy)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = $2,
    revoked_reason = $3
WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeAllRefreshTokensForUserParams struct {
	UserID        uuid.UUID
	RevokedAt     *time.Time
	RevokedReason *string
}

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, arg.UserID, arg.RevokedAt, arg.RevokedReason)
	return err
}

const revokeRefreshTokenSession = `-- name: RevokeRefreshTokenSession :exec
UPDATE refresh_tokens
SET revoked_at = $2,
    revoked_reason = $3
WHERE session_id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenSessionParams struct {
	SessionID     uuid.UUID
	RevokedAt     *time.Time
	RevokedReason *string
}

func (q *Queries) RevokeRefreshTokenSession(ctx context.Context, arg RevokeRefreshTokenSessionParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenSession, arg.SessionID, arg.RevokedAt, arg.RevokedReason)
	return err
}
