// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: super_admin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSuperAdmin = `-- name: CreateSuperAdmin :one
INSERT INTO super_admin_users (email, full_name, password_hash, role, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, full_name, password_hash, role, status, totp_secret, totp_enrolled_at, failed_login_attempts, locked_until, last_login_at, created_at, updated_at
`

type CreateSuperAdminParams struct {
	Email        string
	FullName     string
	PasswordHash string
	Role         SuperAdminRole
	Status       SuperAdminStatus
}

func (q *Queries) CreateSuperAdmin(ctx context.Context, arg CreateSuperAdminParams) (SuperAdminUser, error) {
	row := q.db.QueryRow(ctx, createSuperAdmin,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i SuperAdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuperAdminByEmail = `-- name: GetSuperAdminByEmail :one
SELECT id, email, full_name, password_hash, role, status, totp_secret, totp_enrolled_at, failed_login_attempts, locked_until, last_login_at, created_at, updated_at FROM super_admin_users WHERE email = $1
`

// email — citext, поэтому сравнение регистронезависимое на стороне БД
func (q *Queries) GetSuperAdminByEmail(ctx context.Context, email string) (SuperAdminUser, error) {
	row := q.db.QueryRow(ctx, getSuperAdminByEmail, email)
	var i SuperAdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuperAdminByID = `-- name: GetSuperAdminByID :one
SELECT id, email, full_name, password_hash, role, status, totp_secret, totp_enrolled_at, failed_login_attempts, locked_until, last_login_at, created_at, updated_at FROM super_admin_users WHERE id = $1
`

func (q *Queries) GetSuperAdminByID(ctx context.Context, id uuid.UUID) (SuperAdminUser, error) {
	row := q.db.QueryRow(ctx, getSuperAdminByID, id)
	var i SuperAdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuperAdmins = `-- name: ListSuperAdmins :many
SELECT id, email, full_name, password_hash, role, status, totp_secret, totp_enrolled_at, failed_login_attempts, locked_until, last_login_at, created_at, updated_at FROM super_admin_users ORDER BY created_at
`

func (q *Queries) ListSuperAdmins(ctx context.Context) ([]SuperAdminUser, error) {
	rows, err := q.db.Query(ctx, listSuperAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuperAdminUser{}
	for rows.Next() {
		var i SuperAdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.TotpSecret,
			&i.TotpEnrolledAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerFailedLogin = `-- name: RegisterFailedLogin :exec
UPDATE super_admin_users
SET failed_login_attempts = failed_login_attempts + 1,
    locked_until = COALESCE($2::timestamptz, locked_until)
WHERE id = $1
`

type RegisterFailedLoginParams struct {
	ID          uuid.UUID
	LockedUntil *time.Time
}

// Инкремент и блокировка одним UPDATE: между чтением и записью не должно
// быть окна, в которое влезут параллельные попытки подбора
func (q *Queries) RegisterFailedLogin(ctx context.Context, arg RegisterFailedLoginParams) error {
	_, err := q.db.Exec(ctx, registerFailedLogin, arg.ID, arg.LockedUntil)
	return err
}

const registerSuccessfulLogin = `-- name: RegisterSuccessfulLogin :exec
UPDATE super_admin_users
SET failed_login_attempts = 0,
    locked_until = NULL,
    last_login_at = $2
WHERE id = $1
`

type RegisterSuccessfulLoginParams struct {
	ID          uuid.UUID
	LastLoginAt *time.Time
}

func (q *Queries) RegisterSuccessfulLogin(ctx context.Context, arg RegisterSuccessfulLoginParams) error {
	_, err := q.db.Exec(ctx, registerSuccessfulLogin, arg.ID, arg.LastLoginAt)
	return err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE super_admin_users
SET totp_secret = $2,
    totp_enrolled_at = $3
WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID             uuid.UUID
	TotpSecret     *string
	TotpEnrolledAt *time.Time
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecret, arg.TotpEnrolledAt)
	return err
}

const updateSuperAdminRole = `-- name: UpdateSuperAdminRole :one
UPDATE super_admin_users SET role = $2 WHERE id = $1
RETURNING id, email, full_name, password_hash, role, status, totp_secret, totp_enrolled_at, failed_login_attempts, locked_until, last_login_at, created_at, updated_at
`

type UpdateSuperAdminRoleParams struct {
	ID   uuid.UUID
	Role SuperAdminRole
}

func (q *Queries) UpdateSuperAdminRole(ctx context.Context, arg UpdateSuperAdminRoleParams) (SuperAdminUser, error) {
	row := q.db.QueryRow(ctx, updateSuperAdminRole, arg.ID, arg.Role)
	var i SuperAdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSuperAdminStatus = `-- name: UpdateSuperAdminStatus :one
UPDATE super_admin_users SET status = $2 WHERE id = $1
RETURNING id, email, full_name, password_hash, role, status, totp_secret, totp_enrolled_at, failed_login_attempts, locked_until, last_login_at, created_at, updated_at
`

type UpdateSuperAdminStatusParams struct {
	ID     uuid.UUID
	Status SuperAdminStatus
}

func (q *Queries) UpdateSuperAdminStatus(ctx context.Context, arg UpdateSuperAdminStatusParams) (SuperAdminUser, error) {
	row := q.db.QueryRow(ctx, updateSuperAdminStatus, arg.ID, arg.Status)
	var i SuperAdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
