// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, city, address, status, plan, owner_name, phone, email, trial_ends_at, activation_code, activation_code_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, city, address, status, plan, employees, owner_name, phone, email, last_active_at, trial_ends_at, suspended_reason, activation_code, activation_code_expires_at, created_at, updated_at
`

type CreateTenantParams struct {
	Name                    string
	City                    string
	Address                 string
	Status                  TenantStatus
	Plan                    TenantPlan
	OwnerName               string
	Phone                   string
	Email                   string
	TrialEndsAt             *time.Time
	ActivationCode          *string
	ActivationCodeExpiresAt *time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.City,
		arg.Address,
		arg.Status,
		arg.Plan,
		arg.OwnerName,
		arg.Phone,
		arg.Email,
		arg.TrialEndsAt,
		arg.ActivationCode,
		arg.ActivationCodeExpiresAt,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Status,
		&i.Plan,
		&i.Employees,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.LastActiveAt,
		&i.TrialEndsAt,
		&i.SuspendedReason,
		&i.ActivationCode,
		&i.ActivationCodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, city, address, status, plan, employees, owner_name, phone, email, last_active_at, trial_ends_at, suspended_reason, activation_code, activation_code_expires_at, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Status,
		&i.Plan,
		&i.Employees,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.LastActiveAt,
		&i.TrialEndsAt,
		&i.SuspendedReason,
		&i.ActivationCode,
		&i.ActivationCodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isTenantEmailTaken = `-- name: IsTenantEmailTaken :one
SELECT EXISTS (SELECT 1 FROM tenants WHERE email = $1) AS exists
`

func (q *Queries) IsTenantEmailTaken(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isTenantEmailTaken, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, city, address, status, plan, employees, owner_name, phone, email, last_active_at, trial_ends_at, suspended_reason, activation_code, activation_code_expires_at, created_at, updated_at FROM tenants ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Status,
			&i.Plan,
			&i.Employees,
			&i.OwnerName,
			&i.Phone,
			&i.Email,
			&i.LastActiveAt,
			&i.TrialEndsAt,
			&i.SuspendedReason,
			&i.ActivationCode,
			&i.ActivationCodeExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantActivationCode = `-- name: SetTenantActivationCode :one
UPDATE tenants SET activation_code = $2, activation_code_expires_at = $3 WHERE id = $1
RETURNING id, name, city, address, status, plan, employees, owner_name, phone, email, last_active_at, trial_ends_at, suspended_reason, activation_code, activation_code_expires_at, created_at, updated_at
`

type SetTenantActivationCodeParams struct {
	ID                      uuid.UUID
	ActivationCode          *string
	ActivationCodeExpiresAt *time.Time
}

func (q *Queries) SetTenantActivationCode(ctx context.Context, arg SetTenantActivationCodeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantActivationCode, arg.ID, arg.ActivationCode, arg.ActivationCodeExpiresAt)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Status,
		&i.Plan,
		&i.Employees,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.LastActiveAt,
		&i.TrialEndsAt,
		&i.SuspendedReason,
		&i.ActivationCode,
		&i.ActivationCodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants SET status = $2, suspended_reason = $3 WHERE id = $1
RETURNING id, name, city, address, status, plan, employees, owner_name, phone, email, last_active_at, trial_ends_at, suspended_reason, activation_code, activation_code_expires_at, created_at, updated_at
`

type UpdateTenantStatusParams struct {
	ID              uuid.UUID
	Status          TenantStatus
	SuspendedReason *string
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus, arg.ID, arg.Status, arg.SuspendedReason)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Status,
		&i.Plan,
		&i.Employees,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.LastActiveAt,
		&i.TrialEndsAt,
		&i.SuspendedReason,
		&i.ActivationCode,
		&i.ActivationCodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
