// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const assignTicket = `-- name: AssignTicket :one
UPDATE support_tickets SET assignee_id = $2 WHERE id = $1
RETURNING id, tenant_id, subject, status, priority, assignee_id, contact_name, last_message_at, created_at, updated_at
`

type AssignTicketParams struct {
	ID         uuid.UUID
	AssigneeID *uuid.UUID
}

func (q *Queries) AssignTicket(ctx context.Context, arg AssignTicketParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, assignTicket, arg.ID, arg.AssigneeID)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ContactName,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketMessage = `-- name: CreateTicketMessage :one
INSERT INTO support_ticket_messages (ticket_id, author, author_name, author_id, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, author, author_name, author_id, body, sent_at
`

type CreateTicketMessageParams struct {
	TicketID   uuid.UUID
	Author     TicketMessageAuthor
	AuthorName string
	AuthorID   *uuid.UUID
	Body       string
}

func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (SupportTicketMessage, error) {
	row := q.db.QueryRow(ctx, createTicketMessage,
		arg.TicketID,
		arg.Author,
		arg.AuthorName,
		arg.AuthorID,
		arg.Body,
	)
	var i SupportTicketMessage
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Author,
		&i.AuthorName,
		&i.AuthorID,
		&i.Body,
		&i.SentAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, tenant_id, subject, status, priority, assignee_id, contact_name, last_message_at, created_at, updated_at FROM support_tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ContactName,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT id, ticket_id, author, author_name, author_id, body, sent_at FROM support_ticket_messages WHERE ticket_id = $1 ORDER BY sent_at
`

func (q *Queries) ListTicketMessages(ctx context.Context, ticketID uuid.UUID) ([]SupportTicketMessage, error) {
	rows, err := q.db.Query(ctx, listTicketMessages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportTicketMessage{}
	for rows.Next() {
		var i SupportTicketMessage
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Author,
			&i.AuthorName,
			&i.AuthorID,
			&i.Body,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, tenant_id, subject, status, priority, assignee_id, contact_name, last_message_at, created_at, updated_at FROM support_tickets
WHERE ($1::uuid IS NULL OR tenant_id = $1::uuid)
  AND ($2::ticket_status IS NULL OR status = $2::ticket_status)
ORDER BY last_message_at DESC
`

type ListTicketsParams struct {
	TenantID *uuid.UUID
	Status   *TicketStatus
}

// Фильтр по назначению (конкретный сотрудник / «без назначения») — в Go-коде
// репозитория: тикетов на суперадминку — десятки-сотни, а не миллионы, третий
// optional-параметр вперемешку с sqlc.narg усложнил бы запрос сильнее, чем
// экономит.
func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportTicket{}
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.ContactName,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketPriority = `-- name: UpdateTicketPriority :one
UPDATE support_tickets SET priority = $2 WHERE id = $1
RETURNING id, tenant_id, subject, status, priority, assignee_id, contact_name, last_message_at, created_at, updated_at
`

type UpdateTicketPriorityParams struct {
	ID       uuid.UUID
	Priority TicketPriority
}

func (q *Queries) UpdateTicketPriority(ctx context.Context, arg UpdateTicketPriorityParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, updateTicketPriority, arg.ID, arg.Priority)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ContactName,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE support_tickets SET status = $2 WHERE id = $1
RETURNING id, tenant_id, subject, status, priority, assignee_id, contact_name, last_message_at, created_at, updated_at
`

type UpdateTicketStatusParams struct {
	ID     uuid.UUID
	Status TicketStatus
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.ID, arg.Status)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ContactName,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
